amp:
  data_iface: ens18
  
  aether_roc:
    helm:
      chart_ref: aether/aether-roc-umbrella
      chart_version: 2.1.35

  atomix:
    helm:
      chart_ref: atomix/atomix-runtime
      chart_version: 0.1.8

  onosproject:
    helm:
      chart_ref: onosproject/onos-operator
      chart_version: 0.5.6

  store:
    lpp:
      version: v0.0.24